version: '3.8'
services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: user          # Пользователь PostgreSQL
      POSTGRES_PASSWORD: password  # Пароль PostgreSQL
      POSTGRES_DB: db              # Название базы данных
    ports:
      - "5432:5432"  # Проброс порта (внешний:внутренний)
    volumes:
      - pg_data:/var/lib/postgresql/data # Привязка к внешнему хранилищу для сохранения данных
volumes:
  pg_data:
    driver: local