spring:
  application:
  name: T1_Club_Card-Maven
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml

server:
  port: 8080

qr-code-size: 480
